### ISSUE TITLE
agnoster-bash not showing the python virtualenv workon session

### ISSUE THREAD

**Issue by MacFlurry** [speedenator/agnoster-bash#6]
Hello,

I usually work with Python virtualenv. 
example: 

```
$ mkvirtualenv mynewenv
$ workon mynewenv
```
And the new prompt will be:

`(mynewenv)$ `

but agnoster-bash not showing the` (mynewenv)$ `

could you help on that ?

thanks a lot.

**Comment by speedenator** [comment]
Can you provide a screenshot?
Note that agnoster overrides the prompt, so when you workon mynewenv it will still likely have the existing prompt. Granted, that isn't a bad feature request.

**Comment by MacFlurry** [comment]
hello,

<img width="515" alt="screen shot 2017-09-16 at 18 23 44" src="https://user-images.githubusercontent.com/8139322/30513921-47b6f76a-9b0c-11e7-9cf2-247b6b6f55e1.png">

thanks for your help :-)

**Comment by millefalcon** [comment]
I have fixed it and made a pull request.

**Comment by speedenator** [comment]
Ah thanks - let me take care of that!

**Comment by speedenator** [comment]
PR merged, closing!

**Comment by kirk86** [comment]
@speedenator I'm having the same issue. Does this PR solve the issue since I cloned agnoster theme but doesn't seem to be working.

![image](https://user-images.githubusercontent.com/2902390/82210259-9a8ce580-9906-11ea-8c54-8c56b04286fd.png)

Another issue that I'm facing is that when changing the background colour of the user info into blue the white prompt_segment seems to be blue as well so navigating into folders makes the prompt_segment disappear.
![image](https://user-images.githubusercontent.com/2902390/82210544-34549280-9907-11ea-825a-9693d93219cf.png)
 
as you can see I'm loosing the white right arrow when changing the colour to blue instead of cyan as in the first screenshot above.
